# Generated by Django 3.2.16 on 2023-06-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='Category',
            field=models.CharField(choices=[(None, 'Category'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('home', 'Home and Kitchen'), ('beauty', 'Beauty and Personal Care'), ('books', 'Books'), ('jewelry', 'Jewelry'), ('pet_supplies', 'Pet Supplies'), ('pets', 'Pets'), ('sports_and_outdoors', 'Sports and Outdoors')], max_length=20),
        ),
    ]
